In [1]:
# import file and save to numpy array

import csv
with open('winequality-red.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))
import numpy as np
wines = np.array(wines[1:], dtype=np.float)

In [2]:
# rows, columns of data
wines.shape

(1599, 12)

In [3]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [4]:
# create an array of 0's
import numpy as np
empty_array = np.zeros((3,4))

In [5]:
empty_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# create an array of random numbers
np.random.rand(3,4)

array([[0.61262779, 0.44793228, 0.52200778, 0.64061971],
       [0.68452943, 0.88781477, 0.38216069, 0.2463115 ],
       [0.08005654, 0.41902976, 0.64101759, 0.42576564]])

In [10]:
# index numpy arrays
# row 3, column 4
wines[2, 3]



2.3

In [9]:
# slicing numpy arrays
# select first 3 items of column 4
wines[0:3,3]
# same as wines[:3,3]

array([1.9, 2.6, 2.3])